version: '3.4'

volumes:
  postgres-data:  

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: GATEWAY/Dockerfile
    ports:
      - "5200:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  service-identity:
    image: service-identity
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Identity.API/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - postgres_identity
    hostname: service-identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
# database
  postgres_identity:
    container_name: ps-identity
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: service-identity
      TZ: UTC
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  mynetwork: